service: svc-sls-extract-pdf-v2

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: python3.9
  stage: prod
  region: us-east-2
  memorySize: 256
  timeout: 60
  environment:
    AWS_S3_ACCESS_KEY_ID: ${file(./env.json):AWS_S3_ACCESS_KEY_ID}
    AWS_S3_SECRET_ACCESS_KEY: ${file(./env.json):AWS_S3_SECRET_ACCESS_KEY}
    AWS_S3_REGION: ${file(./env.json):AWS_S3_REGION}
    API_HOST_SERVERLESS: ${file(./env.json):API_HOST_SERVERLESS}
    API_HOST_DB_RELATIONAL: ${file(./env.json):API_HOST_DB_RELATIONAL}
    API_HOST_OCR_EXTRACT: ${file(./env.json):API_HOST_OCR_EXTRACT}
    API_HOST_OCR_EXTRACT_V2: ${file(./env.json):API_HOST_OCR_EXTRACT_V2}
  ecr:
    images:
      extractpdfimage:
        path: ./

package:
  individually: true
  patterns:
    - '!data/**'
    - '!tmp/**'

functions:
  main:
    image: extractpdfimage
    events:
      - s3:
          bucket: extract-bank-pdf
          event: s3:ObjectCreated:*
          existing: true
          forceDeploy: true